#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ── Hints — declared below the marker, library above is untouched ─────────
INSTALL_URL="https://cli.github.com/"
MSI_URL="https://github.com/cli/cli/releases/latest/download/gh_windows_amd64.msi"

# _gh_dirs — every real directory on this machine that holds gh.exe.
# Checks PATH first, then the standard per-user and machine-wide locations.
_gh_dirs() {
  local out="" d part
  IFS=':' read -ra _parts <<<"${PATH:-}"
  for part in "${_parts[@]}"; do
    [[ -n "$part" && -x "$part/gh.exe" ]] || continue
    case ":$out:" in *":$part:"*) continue ;; esac
    out="${out:+$out:}$part"
  done
  if command -v cygpath >/dev/null 2>&1; then
    for d in "$LOCALAPPDATA/Programs/gh/bin" \
             "$USERPROFILE/.local/bin" \
             "$PROGRAMFILES/GitHub CLI" \
             "/c/Program Files/GitHub CLI" \
             "/c/ProgramData/chocolatey/bin"; do
      d=$(cygpath -u "$d" 2>/dev/null) || continue
      [[ -x "$d/gh.exe" ]] || continue
      case ":$out:" in *":$d:"*) continue ;; esac
      out="${out:+$out:}$d"
    done
  fi
  printf '%s' "$out"
  return 0
}

_gh_bin=""

# _refresh_gh — find gh.exe, prefer one already on PATH, and expose it as a
# shell function so every later stage can just call `gh` (dirs with spaces
# need the quoted form).
_refresh_gh() {
  local dirs chosen
  dirs=$(_gh_dirs)
  [[ -n "$dirs" ]] || { _gh_bin=""; return 1; }
  chosen="${dirs%%:*}"
  _gh_bin="$chosen/gh.exe"
  gh() { "$_gh_bin" "$@"; }
  return 0
}

banner "GitHub CLI (gh) — install & sign in"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "GitHub CLI — verify the installation"
say "Checking whether gh is already on this machine before downloading anything."
note "official site: $INSTALL_URL"

if _refresh_gh; then
  _gh_ver=$(gh --version | head -n1)
  printf '  %s✓ found%s %s\n' "$GREEN" "$RESET" "$_gh_ver"
  say "location: $(dirname "$_gh_bin")"
  note "Already installed — this wizard verifies it and gets you signed in."
  pause "Press Enter to continue"
else
  warn "gh was not found in the usual locations."
  printf '\n'; say "Install it with one of these, then re-run this wizard:"
  if command -v winget.exe >/dev/null 2>&1; then
    printf '  %s•%s winget (official, needs an Administrator terminal):\n' "$BLUE" "$RESET"
    printf '      winget install --id GitHub.cli --exact\n'
  else
    printf '  %s•%s winget is not available here — use the MSI:\n' "$BLUE" "$RESET"
  fi
  printf '  %s•%s MSI installer (opens the download):\n' "$BLUE" "$RESET"
  printf '      %s\n' "$MSI_URL"
  printf '  %s•%s per-user install that needs no admin at all:\n' "$BLUE" "$RESET"
  printf '      unpack the release .zip and put its bin/ on your user PATH\n'
  open_url "$INSTALL_URL"
  open_url "$MSI_URL"
  if ! confirm "I've installed gh — check again?"; then
    SKIPPED+=("gh CLI installation — re-run this wizard afterwards")
    say "Stopping here; everything else needs gh present."; finish; exit 0
  fi
  if ! _refresh_gh; then
    warn "still can't find gh.exe — open a NEW terminal so PATH refreshes, then re-run."
    SKIPPED+=("gh CLI installation")
    finish; exit 0
  fi
  printf '  %s✓ found%s %s\n' "$GREEN" "$RESET" "$(gh --version | head -n1)"
  pause "Press Enter to continue"
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "GitHub CLI — make sure it's on PATH"
say "A new terminal must be able to run 'gh' by typing its name."
note "This window is the one exception — it inherited an older PATH."

_gh_dir=$(dirname "$_gh_bin")
case ":$PATH:" in
  *":$_gh_dir:"*) printf '  %s✓ ready%s %s is already on this PATH\n' "$GREEN" "$RESET" "$_gh_dir" ;;
  *)              printf '  %s!%s this shell only: %s → added for this session\n' "$YELLOW" "$RESET" "$_gh_dir"
                  PATH="$_gh_dir:$PATH" ;;
esac

# _fresh_gh — resolve gh.exe the way a brand-new terminal would: from the
# persisted registry PATH, not from this script's already-patched environment.
# Prints the full path on success, nothing on failure.
_fresh_gh() {
  command -v powershell.exe >/dev/null 2>&1 || return 1
  powershell.exe -NoProfile -Command \
    "\$p=([Environment]::GetEnvironmentVariable('Path','Machine')+';'+[Environment]::GetEnvironmentVariable('Path','User')) -split ';'; (\$p | Where-Object { \$_ -and (Test-Path (Join-Path \$_ 'gh.exe')) } | ForEach-Object { Join-Path \$_ 'gh.exe' } | Select-Object -First 1)" \
    2>/dev/null | tr -d '\r' | head -n1
}

# Persist to the Windows *user* PATH (no admin needed) when it's missing there.
# Decisions come from PowerShell *exit codes* so this works on a non-English
# Windows too.
if command -v powershell.exe >/dev/null 2>&1 && command -v cygpath >/dev/null 2>&1; then
  _win_dir=$(cygpath -w "$_gh_dir" 2>/dev/null) || _win_dir=""
  if [[ -n "$_win_dir" ]]; then
    if powershell.exe -NoProfile -Command \
        "[Environment]::GetEnvironmentVariable('Path','User').Split(';') -contains '$_win_dir'" \
        >/dev/null 2>&1; then
      printf '  %s✓ persisted%s already on the Windows user PATH\n' "$GREEN" "$RESET"
    else
      if powershell.exe -NoProfile -Command \
          "\$c=[Environment]::GetEnvironmentVariable('Path','User'); [Environment]::SetEnvironmentVariable('Path',(\$c.TrimEnd(';')+';$_win_dir'),'User')" \
          >/dev/null 2>&1; then
        printf '  %s✓ persisted%s added to the Windows user PATH (no admin needed)\n' "$GREEN" "$RESET"
        note "open a new terminal to pick it up"
      else
        warn "couldn't update the user PATH automatically"
        SKIPPED+=("add $_win_dir to your user PATH by hand")
      fi
    fi
  fi
else
  note "couldn't reach powershell.exe — skipping the persistent PATH update"
fi

_fresh=$(_fresh_gh | head -n1)
if [[ -n "$_fresh" ]]; then
  printf '  %s✓ verified%s a new terminal resolves gh → %s\n' "$GREEN" "$RESET" "$_fresh"
else
  warn "a fresh terminal still can't see gh — check your user PATH manually"
  SKIPPED+=("gh on PATH for new terminals")
fi
pause "Press Enter to continue"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "GitHub — sign in"
if gh auth status >/dev/null 2>&1; then
  printf '  %s✓ already signed in%s\n' "$GREEN" "$RESET"
  gh auth status 2>&1 | sed 's/^/      /' || true
  pause "Press Enter to continue"
else
  say "This is the interactive part — gh will ask you a few questions."
  open_url "https://github.com/login/device"
  printf '\n'; say "When gh prompts, answer:"
  step "What account?            → GitHub.com"
  step "Protocol?                → HTTPS"
  step "Authenticate Git with it? → No   (your remote is SSH: git@github.com)"
  step "How to sign in?          → Login with a web browser"
  printf '\n'
  step "It shows a one-time code like XXXX-XXXX — copy it."
  step "Press Enter, your browser opens github.com/login/device."
  step "Paste the code, approve, come back here."
  printf '\n'
  note "A token is never shown to this wizard — gh stores it in the"
  note "Windows Credential Manager, which is the right place for it."
  pause "Press Enter to start the login flow"

  gh auth login || true

  if gh auth status >/dev/null 2>&1; then
    printf '\n  %s✓ signed in%s\n' "$GREEN" "$RESET"
  else
    warn "login didn't complete."
    if confirm "Try again?"; then
      gh auth login || true
    fi
    if ! gh auth status >/dev/null 2>&1; then
      SKIPPED+=("gh sign-in — run 'gh auth login' yourself later")
      warn "skipping ahead; you can sign in any time with:  gh auth login"
    fi
  fi
  pause "Press Enter to continue"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "GitHub — verify your identity"
if ! gh auth status >/dev/null 2>&1; then
  warn "not signed in yet — skipping. Run 'gh auth login' when ready."
  SKIPPED+=("identity check")
else
  _gh_user=$(gh api user --jq .login 2>/dev/null || true)
  _gh_plan=$(gh api user --jq '.plan.name // "n/a"' 2>/dev/null || true)
  _gh_scopes=$(gh auth status 2>&1 | grep -o 'account [^)]*' | head -n1 || true)
  printf '  %s✓ account%s %s\n' "$GREEN" "$RESET" "${_gh_user:-unknown}"
  note "plan  : ${_gh_plan:-n/a}"
  note "scopes: ${_gh_scopes:-see 'gh auth status'}"

  printf '\n'; say "Live check — the newest issues on your own repo:"
  if gh issue list --repo springkai66/deep-pi --limit 3 2>/dev/null | sed 's/^/      /'; then
    printf '  %s✓ verified%s talk to the GitHub API as %s\n' "$GREEN" "$RESET" "${_gh_user:-you}"
  else
    warn "couldn't list issues (repo may have none, or it's private/renamed)"
    printf '  %s✓ verified%s API responds, which is enough\n' "$GREEN" "$RESET"
  fi
fi
pause "Press Enter to continue"

# ── Stage 5 (optional) ────────────────────────────────────────────────────
stage "Git — let gh handle HTTPS credentials (optional)"
if ! gh auth status >/dev/null 2>&1; then
  warn "not signed in — skipping this optional stage."
  SKIPPED+=("gh git credential helper (optional)")
else
  note "Your origin remote is:  git@github.com:springkai66/deep-pi.git"
  say "That's SSH, so it keeps working exactly as it does now whether or not"
  say "you set this up. This only matters if you ever clone via HTTPS."
  printf '\n'
  if confirm "Run 'gh auth setup-git' anyway?"; then
    if gh auth setup-git 2>/dev/null; then
      printf '  %s✓ configured%s git credential helper for github.com\n' "$GREEN" "$RESET"
    else
      warn "gh auth setup-git failed — harmless, your SSH remote is unaffected"
      SKIPPED+=("gh git credential helper")
    fi
  else
    note "skipped — fine to leave off, SSH is unaffected"
  fi
fi
pause "Press Enter to continue"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Final check"
_new_term=$(_fresh_gh | head -n1)
if [[ -n "$_new_term" ]]; then
  printf '  %s✓ installed%s new terminals resolve gh\n' "$GREEN" "$RESET"
  note "    $_new_term"
else
  warn "not resolvable from a fresh terminal yet"
  SKIPPED+=("gh on PATH for new terminals")
fi

if gh auth status >/dev/null 2>&1; then
  _final_user=$(gh api user --jq .login 2>/dev/null || echo "?")
  printf '  %s✓ signed in%s as %s\n' "$GREEN" "$RESET" "$_final_user"
else
  warn "not signed in"
  SKIPPED+=("gh sign-in — run 'gh auth login'")
fi

printf '\n'
say "Handy first commands:"
printf '      gh repo view springkai66/deep-pi\n'
printf '      gh issue list\n'
printf '      gh pr status\n'
printf '      gh run list      # CI runs for this repo\n'
printf '\n'
note "This wizard never downloaded anything and never touched CI secrets."
note "DeepPi's release workflow still needs TAURI_SIGNING_PRIVATE_KEY and"

finish

printf '  %s⚠ Not covered here, and still yours to set up:%s\n' "$YELLOW" "$RESET"
note "  • CI secrets for .github/workflows/release.yml:"
note "      TAURI_SIGNING_PRIVATE_KEY, TAURI_SIGNING_PRIVATE_KEY_PASSWORD,"
note "      DEEPPI_UPDATER_PUBLIC_KEY, DEEPPI_WINDOWS_CERTIFICATE_BASE64,"
note "      DEEPPI_WINDOWS_CERTIFICATE_PASSWORD"
note "    Those are real private keys/certs — the wizard deliberately stops short"
note "    of guessing at them. Ask for the CI-secrets wizard when you're ready."
printf '\n'
